
version: "3.8"

services:

  #  PostgreSQL service
  postgres-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: book-storage-spring-rest-postgres

  #  App
  book-storage-spring-rest-postgres:
    depends_on:
      - postgres-db
    image: book-storage-spring-rest-postgres-image
    ports:
      # Pay attention to 9080 port!!!
      - "9080:8080"
    environment:
      SPRING_APPLICATION_YML: '{
          "spring.datasource.url" : "jdbc:postgresql://postgres-db:5432/book-storage-spring-rest-postgres",
          "spring.datasource.username" : "postgres",
          "spring.datasource.password" : "root",
          "spring.datasource.driver-class-name" : "org.postgresql.Driver",
          
          "spring.datasource.initialization-mode" : "always",
          "spring.datasource.continue-on-error" : "true",
          "spring.datasource.max-wait" : "30000",
          
          "spring.jpa.show-sql" : "true",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.jpa.open-in-view" : "false",
          
          "security.jwt.requestHeader": "Authorization",
          "security.jwt.secretKey": "mySecretKey-mySecretKey-mySecretKey",
          "security.jwt.validity": "3600"
      }'


