spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/book-storage-spring-rest-postgres
    url: jdbc:postgresql://postgres-db:5432/book-storage-spring-rest-postgres
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    requestHeader: Authorization
    secretKey: mySecretKey-mySecretKey-mySecretKey
    validity: 3600

