spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-storage-spring-rest-postgres
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

